# Generated by Django 3.0.4 on 2020-05-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200507_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='intagram_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_no',
            field=models.IntegerField(null=True),
        ),
    ]
