# Generated by Django 3.0.4 on 2020-05-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200513_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_no',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_no',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
